package com.example.cricketscoreapp.model

data class User(
    val id: String? = null, // ID is auto-generated by MockAPI
    val userId: String, // Unique User ID
    val username: String, // Unique User ID
    val password: String,
    val email: String,
    val createdAt: String? = null,
)